version: 2.1
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/playwright:v1.25.2-focal@sha256:29587125552f35750644b9f6cc28df3fddd21123f7c42a8e8c681c4502db1108
    steps:
      - checkout
      - run: ls -la /ms-playwright
